### ISSUE TITLE
Scores don't match genome with GARealGenome

### ISSUE THREAD

**Issue by gmfricke** [B0RJA/GAlib-mpi#4]
I have been working with GAlib-mpi for a month or so and believe the code below shows a bug. I have been trying to resolve it but am wondering if you have any insights into the problem.

I compile the code into an executable called bug_example. When I run mpirun -n 1 ./bug_example the objective and score functions give the same output for the same genome. When I run with mpirun -n 2 ./bug_example they no longer give the same output:

$mpirun -n 1 ./bug_example:
The GA found an optimum at: 7.90101, 7.90101 with score: 0.00354479
Objective function: 0.00354479
GA result:
x = 7.901015, y = 7.901015

$mpirun -n 2 ./bug_example:
The GA found an optimum at: 12.0348, 6.25647 with score: 0.0719149
Objective function: 0.573609
GA result:
x = 12.034814, y = 6.256466

**Comment by B0RJA** [comment]
In order to obtain the same results you must use the same seed:
mpirun -np 1 example seed 1234
mpirun -np 2 example seed 1234

Anyway, I suggest using GAUL:
https://gist.github.com/B0RJA/9189165

**Comment by gmfricke** [comment]
Thank you very much for your reply. I will give it a try right away and take a look at GAUL.

**Comment by gmfricke** [comment]
Setting the seed to be the same on all mpi workers seems to have fixed the issue. Thanks so much for helping. You kept 6 weeks of work from going down the drain!
