### ISSUE TITLE
How does the parallelization work 

### ISSUE THREAD

**Issue by ktarila** [B0RJA/GAlib-mpi#5]
This is more of a question, rather than issue. Are individuals moved across populations run on different cores/processors, or are they simply run in parallel independent of each other without any migration?

**Comment by B0RJA** [comment]
All individuals exist in all cores/processors. Their scored is shared so each core/processor only computes a subset of the individual scores. In my case this was the time-consuming process.

I suggest to use GAUL:
https://gist.github.com/B0RJA/9189165
