### ISSUE TITLE
Create a Copy of a Population

### ISSUE THREAD

**Issue by MichaelTettehK** [B0RJA/GAlib-mpi#7]
I just want to find out, how do you create a copy of a population that allows you to modify or remove individuals from it without affecting the original population. I have seen `clone() and copy methods`.

**Comment by B0RJA** [comment]
All individuals exist in all cores/processors so population is not modified. Their scored is shared so each core/processor only computes a subset of the individual scores. In my case this was the time-consuming process. Check the function GAPopulation::DefaultEvaluator in the file ga-mpi/GAPopulation.C. You will find a loop where the individual score is evaluated and then shared.

https://github.com/B0RJA/GAlib-mpi/blob/6c310756ea617b3ecbd0b0bba3f0348314ad77d5/ga-mpi/GAPopulation.C#L37

**Comment by MichaelTettehK** [comment]
@B0RJA Thanks for the response. In my case I want to create a custom selection function which removes individuals if they do not meet a certain criteria This continues in a loop until a single individual is selected and returned.

**Comment by B0RJA** [comment]
Keep the population seems simpler. An option could be to penalize the score of the individuals you want to remove in the mentioned function. In this way they will be eliminated by selection after some generations. Also you will focus more individuals around the optimal solution instead of leaving just one survivor.

**Comment by MichaelTettehK** [comment]
Okay I get the point. The issue is, for my selection I have to prune down the population if certain individuals do not meet a criteria. Essentially this is happening in a loop, so at the end an 
- individual may remain in that case it is returned 

- or a subset of the population may remain in that case one of the individuals is randomly selected and returned.

Basically, this doesn't have to interfere with the main population. I only want to create copy which allows me to prune down the population size by removing individuals.

**Comment by MichaelTettehK** [comment]
I think the `clone` method creates a copy of the population.
